version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]
  


[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
